<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Admin Melodiggers</title>
</head>
<body>
<?php //if($_SESSION['role'] === 'admin') { ?><!--}-->
    <nav>
        <ul>
            <li><a href="?route=userList">Utilisateurs</a></li>
            <li><a href="?route=artistList">Artistes</a></li>
            <li><a href="?route=albumList">Albums</a></li>
            <li><a href="?route=mediaList">Medias</a></li>
            <li><a href="?route=reviewList">Reviews</a></li>
            <li><a href="?route=scoreList">Notes</a></li>
        </ul>
    </nav>
<?php //} else { ?>
    <nav>
        <ul>
            <li><a href="?route=logout">Déconnexion</a></li>
        </ul>
    </nav>
<?php //} ?>

<?php
require "templates/admin/$template"
?>
</body>
</html>